Update build-publish.yml

diff --git a/.github/workflows/build-publish.yml b/.github/workflows/build-publish.yml
--- a/.github/workflows/build-publish.yml
+++ b/.github/workflows/build-publish.yml
@@ -42,13 +42,24 @@ jobs:
       - name: Create metadata.json
         id: create_metadata
         run: |
-          # Get the image digest after pushing
-          DIGEST=$(docker inspect elinaf.jfrog.io/test-local-basselm/oceaneeringgg/actions-runner-linux:0.1.2-beta.14 --format '{{index .RepoDigests 0}}' | awk -F '@' '{print $2}')
-          # Ensure the digest format is sha256:sha256:<digest>
-          echo "elinaf.jfrog.io/test-local-basselm/oceaneeringgg/actions-runner-linux:0.1.2-beta.14@${DIGEST}" > metadata.json
+          # Inspect the pushed image and extract the digest
+          DIGEST=$(docker buildx imagetools inspect elinaf.jfrog.io/test-local-basselm/oceaneeringgg/actions-runner-linux:0.1.2-beta.14 --format '{{.Digest}}')
+          
+          # Echo the digest to see the output
+          echo "Image digest: $DIGEST"
+      
+          if [ -z "$DIGEST" ]; then
+            echo "Error: Unable to retrieve image digest"
+            exit 1
+          fi
+      
+          # Ensure the correct format for the metadata.json
+          echo "{\"name\": \"elinaf.jfrog.io/test-local-basselm/oceaneeringgg/actions-runner-linux\", \"digest\": \"sha256:${DIGEST}\"}" > metadata.json
+      
           # Log the content of metadata.json for debugging
           echo "Content of metadata.json:"
           cat metadata.json
+
 
       - name: Deploy build-info
         run: |
